// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfuF9Ywk9yCuzlTPLzBanIwvtB2RCI6wA',
    appId: '1:521991486354:web:a538fdc89dc392f4611f4b',
    messagingSenderId: '521991486354',
    projectId: 'the-iq-hub',
    authDomain: 'the-iq-hub.firebaseapp.com',
    storageBucket: 'the-iq-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTNmFHMfobcPOd1BJwB3ZV2c22NCVYPf4',
    appId: '1:521991486354:android:d2c5727dcf7df113611f4b',
    messagingSenderId: '521991486354',
    projectId: 'the-iq-hub',
    storageBucket: 'the-iq-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUX538kjMHVMSGP8EzvVy6ysOKV31Sz44',
    appId: '1:521991486354:ios:accab13a35b86219611f4b',
    messagingSenderId: '521991486354',
    projectId: 'the-iq-hub',
    storageBucket: 'the-iq-hub.appspot.com',
    iosClientId: '521991486354-48nch8092ebkjlvf2pm83gsdafudiuap.apps.googleusercontent.com',
    iosBundleId: 'com.example.theIqHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUX538kjMHVMSGP8EzvVy6ysOKV31Sz44',
    appId: '1:521991486354:ios:accab13a35b86219611f4b',
    messagingSenderId: '521991486354',
    projectId: 'the-iq-hub',
    storageBucket: 'the-iq-hub.appspot.com',
    iosClientId: '521991486354-48nch8092ebkjlvf2pm83gsdafudiuap.apps.googleusercontent.com',
    iosBundleId: 'com.example.theIqHub',
  );
}
